name: Build and Package OGDF-Tmap Libraries

on:
  workflow_dispatch:
    # workflow_dispatch allows manual triggering of the workflow, as long as the
    # workflow is on the default branch.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build OGDF-Tmap Project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Target OSes
        architecture: [x64, arm64]  # Add support for both x64 and arm64 architectures
        build_type: [Release]  # Build types for matrix
        exclude:
          - os: windows-latest  # Windows doesn't have arm64 support yet in GitHub Actions
            architecture: arm64  # Exclude ARM64 for Windows, only build AMD64


    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Cache CMake build directory
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ matrix.architecture }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-${{ matrix.architecture }}-${{ matrix.build_type }}
          ${{ runner.os }}-cmake-${{ matrix.architecture }}
          ${{ runner.os }}-cmake

    - name: Cache dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: apt-cache-${{ runner.os }}-${{ matrix.architecture }}
        restore-keys: apt-cache-${{ runner.os }}-${{ matrix.architecture }}

    - name: Cache dependencies (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/cache@v4
      with:
        path: /Users/${{ github.actor }}/Library/Caches/Homebrew
        key: brew-cache-${{ runner.os }}-${{ matrix.architecture }}
        restore-keys: brew-cache-${{ runner.os }}-${{ matrix.architecture }}

    - name: Cache dependencies (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: choco-cache-${{ runner.os }}-${{ matrix.architecture }}
        restore-keys: choco-cache-${{ runner.os }}-${{ matrix.architecture }}

    - name: Set up CMake
      uses: lukka/get-cmake@v3.30.4

    - name: Install dependencies (Linux x64/arm64)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y build-essential libx11-dev

    - name: Install dependencies (macOS x64/arm64)
      if: matrix.os == 'macos-latest'
      run: brew install cmake libx11 llvm

    - name: Install dependencies (Windows x64)
      if: matrix.os == 'windows-latest'
      run: choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools

    - name: Create build directory
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          mkdir build -Force
        else
          mkdir -p build
        fi
      shell: bash

    - name: Set up environment for LLVM (macOS Intel/ARM64)
      if: matrix.os == 'macos-latest'
      run: |
        if [[ $(uname -m) == 'arm64' ]]; then
          echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        else
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
        fi

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_SHARED_LIBS=ON
      working-directory: ${{ github.workspace }}

    - name: Build (Linux & macOS)
      if: matrix.os != 'windows-latest'
      run: cmake --build build --config ${{ matrix.build_type }} -- -j$(nproc) VERBOSE=1
      working-directory: ${{ github.workspace }}

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake --build build --config ${{ matrix.build_type }} -- /m
      working-directory: ${{ github.workspace }}

    # Use PowerShell for Windows and sed for Linux/macOS to extract the version
    - name: Determine version number (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        echo "version=$(sed -n 's/^project.*VERSION \([0-9.]*\).*$/\1/p' CMakeLists.txt)" >> $GITHUB_ENV
        pwd
        ls -alh ./
        ls -alh build/
        ls -alh build/dist/
        ls -alh build/dist/lib/

    - name: Determine version number (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        $version = (Select-String -Path "CMakeLists.txt" -Pattern 'VERSION ([0-9]+\.[0-9]+\.[0-9]+)').Matches.Groups[1].Value
        echo "version=$version" >> $env:GITHUB_ENV

    - name: Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ogdf-tmap-libs-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.build_type }}-v${{ env.version }}
        if-no-files-found: error
        path: |
          build/dist/*
          include/
